import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { VitalPlusLogo } from "@/components/VitalPlusLogo";

import {
  SidebarProvider,
  Sidebar,
  SidebarHeader,
  SidebarFooter,
  SidebarContent,
  SidebarGroup,
  SidebarTrigger,
} from "@/components/ui/sidebar/sidebar";
import { Button } from "@/components/ui/button";
import { Home, User, Heart } from "lucide-react";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vital+ App",
  description: "Generated by Thomas Osterlehner",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <div className="flex h-screen">
            <Sidebar className="w-64 border-r bg-gray-100 dark:bg-gray-900">
              <SidebarHeader className="p-4 border-b">
              <Link href="/" passHref>
              <VitalPlusLogo />
                </Link>
              </SidebarHeader>
              <SidebarContent className="flex-1 overflow-y-auto p-4">
                <SidebarGroup>
                  <Link href="/">
                    <Button variant="ghost" className="w-full flex justify-start">
                      <Home className="mr-2 h-5 w-5" /> Home
                    </Button>
                  </Link>
                  <Link href="/user">
                    <Button variant="ghost" className="w-full flex justify-start">
                      <User className="mr-2 h-5 w-5" /> User
                    </Button>
                  </Link>
                  <Link href="/gesundheit">
                    <Button variant="ghost" className="w-full flex justify-start">
                      <Heart className="mr-2 h-5 w-5" /> Gesundheit
                    </Button>
                  </Link>
                </SidebarGroup>
              </SidebarContent>
              <SidebarFooter className="p-4 border-t">
                <SidebarTrigger>
                  <Button variant="outline" className="w-full">Toggle Sidebar</Button>
                </SidebarTrigger>
              </SidebarFooter>
            </Sidebar>
            <main className="flex-1 p-4 overflow-y-auto">
              {children}
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
