import type { Metadata } from "next";
import { Geist as geistSans, Geist_Mono as geistMono } from "next/font/google";
import "./globals.css";
import {
  SidebarProvider,
  Sidebar,
  SidebarHeader,
  SidebarFooter,
  SidebarContent,
  SidebarGroup,
  SidebarTrigger,
} from "@/components/ui/sidebar/sidebar";
import { Button } from "@/components/ui/button";
import { Home, User, Heart, Activity, Utensils, Menu } from "lucide-react";
import Link from "next/link";

const geistSansFont = geistSans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMonoFont = geistMono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vital+ App",
  description: "Generated by Thomas Osterlehner",
  icons: {
    icon: '/favicon.svg',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSansFont.variable} ${geistMonoFont.variable} antialiased h-full flex flex-col bg-gradient-to-br from-slate-50 to-blue-50 text-slate-900 overflow-hidden`}
      >
        <SidebarProvider>
          <div className="flex flex-1 overflow-hidden">
            {/* Sidebar */}
            <Sidebar className="w-72 bg-white/80 backdrop-blur-xl border-r border-slate-200/50 shadow-xl shadow-slate-200/20 flex flex-col flex-shrink-0">
              <SidebarHeader className="p-6 border-b border-slate-200/50">
                <Link href="/" passHref>
                  <div className="flex items-center space-x-3">
                    <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-purple-600 rounded-xl flex items-center justify-center">
                      <span className="text-white font-bold text-lg">V+</span>
                    </div>
                    <div>
                      <h1 className="font-bold text-xl text-slate-800">Vital+</h1>
                      <p className="text-sm text-slate-500">Gesundheits-Dashboard</p>
                    </div>
                  </div>
                </Link>
              </SidebarHeader>

              <SidebarContent className="flex-1 overflow-y-auto p-4">
                <SidebarGroup>
                  <nav className="space-y-2">
                    <Link href="/" passHref>
                      <Button
                        variant="ghost"
                        className="w-full flex justify-start items-center h-12 px-4 text-slate-700 hover:bg-blue-50 hover:text-blue-700 rounded-xl transition-all duration-200 group"
                      >
                        <div className="w-10 h-10 bg-blue-100 group-hover:bg-blue-200 rounded-lg flex items-center justify-center mr-3 transition-colors">
                          <Home className="h-5 w-5 text-blue-600" />
                        </div>
                        <span className="font-medium">Dashboard</span>
                      </Button>
                    </Link>

                    <Link href="/user" passHref>
                      <Button
                        variant="ghost"
                        className="w-full flex justify-start items-center h-12 px-4 text-slate-700 hover:bg-green-50 hover:text-green-700 rounded-xl transition-all duration-200 group"
                      >
                        <div className="w-10 h-10 bg-green-100 group-hover:bg-green-200 rounded-lg flex items-center justify-center mr-3 transition-colors">
                          <User className="h-5 w-5 text-green-600" />
                        </div>
                        <span className="font-medium">Profil</span>
                      </Button>
                    </Link>

                    <Link href="/gesundheit" passHref>
                      <Button
                        variant="ghost"
                        className="w-full flex justify-start items-center h-12 px-4 text-slate-700 hover:bg-red-50 hover:text-red-700 rounded-xl transition-all duration-200 group"
                      >
                        <div className="w-10 h-10 bg-red-100 group-hover:bg-red-200 rounded-lg flex items-center justify-center mr-3 transition-colors">
                          <Heart className="h-5 w-5 text-red-600" />
                        </div>
                        <span className="font-medium">Gesundheit</span>
                      </Button>
                    </Link>

                    <Link href="/blutdruck" passHref>
                      <Button
                        variant="ghost"
                        className="w-full flex justify-start items-center h-12 px-4 text-slate-700 hover:bg-purple-50 hover:text-purple-700 rounded-xl transition-all duration-200 group"
                      >
                        <div className="w-10 h-10 bg-purple-100 group-hover:bg-purple-200 rounded-lg flex items-center justify-center mr-3 transition-colors">
                          <Activity className="h-5 w-5 text-purple-600" />
                        </div>
                        <span className="font-medium">Blutdruck</span>
                      </Button>
                    </Link>

                    <Link href="/kalorien" passHref>
                      <Button
                        variant="ghost"
                        className="w-full flex justify-start items-center h-12 px-4 text-slate-700 hover:bg-orange-50 hover:text-orange-700 rounded-xl transition-all duration-200 group"
                      >
                        <div className="w-10 h-10 bg-orange-100 group-hover:bg-orange-200 rounded-lg flex items-center justify-center mr-3 transition-colors">
                          <Utensils className="h-5 w-5 text-orange-600" />
                        </div>
                        <span className="font-medium">Ernährung</span>
                      </Button>
                    </Link>
                  </nav>
                </SidebarGroup>
              </SidebarContent>

              <SidebarFooter className="p-4 border-t border-slate-200/50">
                <SidebarTrigger>
                  <Button 
                    variant="outline" 
                    className="w-full h-12 border-slate-200 hover:bg-slate-50 rounded-xl transition-all duration-200"
                  >
                    <Menu className="mr-2 h-4 w-4" />
                    Sidebar minimieren
                  </Button>
                </SidebarTrigger>
              </SidebarFooter>
            </Sidebar>

            {/* Main Content */}
            <main className="flex-1 overflow-auto bg-transparent">
              <div className="min-h-full p-8">
                {children}
              </div>
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}