import type { Metadata } from "next";
import "./globals.css";
import { Geist as geistSans, Geist_Mono as geistMono } from "next/font/google";
import SidebarLayout from "@/components/sidebar-layout";

const geistSansFont = geistSans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMonoFont = geistMono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vital+ App",
  description: "Generated by Thomas Osterlehner",
  icons: {
    icon: "/favicon.svg?v=7",
  },
  themeColor: "#3B82F6",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de" className="h-full">
      <body
        className={`${geistSansFont.variable} ${geistMonoFont.variable} antialiased h-full flex flex-col bg-gradient-to-br from-slate-50 to-blue-50 text-slate-900 overflow-hidden`}
      >
        <SidebarLayout>{children}</SidebarLayout>
      </body>
    </html>
  );
}
